# Generated by Django 4.0.5 on 2023-02-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
