# Generated by Django 4.0.5 on 2022-07-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0002_status_alter_blacklist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myShop.customers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myShop.status'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myShop.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measured_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myShop.measuredunit'),
        ),
        migrations.AlterField(
            model_name='measuredunit',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
