# Generated by Django 4.0.5 on 2022-07-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_rename_category_name_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
