# Generated by Django 4.0.5 on 2023-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_alter_basket_session_key_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(default='Cash', max_length=25),
        ),
    ]
