# Generated by Django 4.0.5 on 2022-07-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_productinorder_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
