# Generated by Django 4.0.5 on 2023-05-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_alter_orders_delivery_type_alter_orders_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
    ]
