# Generated by Django 4.0.5 on 2023-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0005_remove_productinorder_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='is_active',
            new_name='is_shown',
        ),
    ]
