# Generated by Django 4.0.5 on 2022-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0005_rename_total_amount_productinorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
