# Generated by Django 4.0.5 on 2023-05-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0006_rename_is_active_basket_is_shown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='number',
            new_name='phone',
        ),
    ]
