# Generated by Django 4.0.5 on 2022-08-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0006_productimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
