# Generated by Django 4.0.5 on 2023-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0007_rename_number_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
