# Generated by Django 4.0.5 on 2022-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0008_remove_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
