# Generated by Django 4.0.5 on 2023-05-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0008_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
