# Generated by Django 4.0.5 on 2023-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0009_alter_customers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
    ]
