# Generated by Django 4.0.5 on 2023-05-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
