# Generated by Django 4.0.5 on 2023-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0014_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(default=0),
        ),
    ]
