# Generated by Django 4.0.5 on 2022-10-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0014_alter_basket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True, 'verbose_name_plural': 'customers'},
        ),
    ]
