# Generated by Django 4.0.5 on 2023-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0015_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(),
        ),
    ]
