# Generated by Django 4.0.5 on 2022-10-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0015_alter_customers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
    ]
