# Generated by Django 4.0.5 on 2022-10-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0016_remove_customers_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
