# Generated by Django 4.0.5 on 2023-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0016_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(default=None, max_length=13, null=True, unique=True),
        ),
    ]
